--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-violin-deployment
  labels:
    app: go-violin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-violin
  template:
    metadata:
      labels:
        app: go-violin
    spec:
      containers:
      - name: go-violin-container
        image: localhost:5000/goviolin
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"