apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-violin
spec:
  rules:
  - host: goviolin.com
    http:
      paths:
      - backend:
          service:
            name: go-violin-service
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
